version: '3.9'
services:
  nestjs:
    build:
      context: ./nestjs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./nestjs:/app
      - ./videos:/app/videos
    environment:
      - NODE_ENV=production
