version: '3.9'
services:
  nestjs:
    build:
      context: ./nestjs
      dockerfile: Dockerfile
      args:
        MEDIA_PATH: /app/media
    ports:
      - "3000:3000"
    volumes:
      - ./nestjs:/app
      - media:/app/media
    environment:
      - NODE_ENV=production

volumes:
  media:
    driver: local